# Generated by Django 4.0 on 2024-01-26 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('academy_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name2', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Academy',
                'verbose_name_plural': 'Academies',
                'db_table': 'academy_academy',
                'ordering': ['academy_id'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('parent_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='DNI')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.parent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationRecord',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='CREATED', help_text='Current register status', max_length=15, verbose_name='Status')),
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitude')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Location Record',
                'verbose_name_plural': 'Location Records',
                'db_table': 'academy_location_record',
                'ordering': ['location_id'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='Modified')),
                ('attendance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('UPDATED', 'UPDATED'), ('DELETED', 'DELETED'), ('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=20, verbose_name='Status')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'academy_attendance_record',
                'ordering': ['attendance_id'],
            },
        ),
    ]
